# Generated by Django 2.0.1 on 2018-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.IntegerField()),
                ('p2_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.IntegerField()),
                ('sets_won', models.IntegerField()),
                ('points_scored', models.IntegerField()),
                ('points_against', models.IntegerField()),
            ],
        ),
    ]
